

const sportsData = {
    football: [ 
        { name:'Today',
        data:[{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'

        },
        {
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        }]
    },
    {
       name: 'Tomorrow',
       data:[{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    },
    {
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    },{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    }]
    }
        
],
    Basketball:[ 
        { name:'Today',
        data:[{
            time:'',
            home:'Finland',
            away:'Libya',
            homeOdd:'1.23',
            awayOdd:'1.34',
            drawOdd:'1.12',
            homeScore:'2',
            awayScore:'5',
            homeDouble:'1.6',
            doubleChance:'1.34',
            awayChance:'1.21'
        },
        {
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        }]
    },
    {
       name: 'Tomorrow',
       data:[{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
        doubleChance:'1.32',
        awayChance:'1.23'
    },
    {
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
        doubleChance:'1.32',
        awayChance:'1.23'
    },{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
        homeDouble:'1.23',
        doubleChance:'1.32',
        awayChance:'1.23'
    }]
}
        
],
    Hockey:[ 
        { name:'Today',
        data:[{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },
        {
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        }]
    },
    {
       name: 'Tomorrow',
       data:[{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3'
    },
    {
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3'
    },{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3'
    }]
    }
],
    Baseball:[ 
        { name:'Today',
        data:[{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },
        {
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        },{
            time:'',
            home:'Ghana',
            away:'Libya',
            homeOdd:'1.22',
            awayOdd:'1.23',
            drawOdd:'1.2',
            homeScore:'2',
            awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
        }]
    },
    {
       name: 'Tomorrow',
       data:[{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    },
    {
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    },{
        time:'',
        home:'Ghana',
        away:'Libya',
        homeOdd:'1.22',
        awayOdd:'1.23',
        drawOdd:'1.2',
        homeScore:'2',
        awayScore:'3',
            homeDouble:'1.23',
            doubleChance:'1.32',
            awayChance:'1.23'
    }]
    }
        
],
}
export default sportsData